# Copyright © 2019 Amdocs, Bell Canada
# Copyright (c) 2020 Nordix Foundation, Modifications
# Modifications Copyright © 2020 Nokia
# Modifications Copyright © 2021 Orange
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###################################################################
# This override file enables helm charts for all ONAP applications.
###################################################################
global:
  addTestingComponents: &testing true
  centralizedLoggingEnabled: &centralizedLogging false
  masterPassword: password
  portalFEPort: "9443"
  
  ingress:
    enabled: true
    virtualhost:
      baseurl: "simpledemo.onap.org"

  persistence:
    storageClass: "gp2"

cassandra:
  enabled: true
mariadb-galera:
  enabled: true
  replicaCount: 1
postgres:
  enabled: true
aaf:
  enabled: true
aai:
  enabled: true
  aai-graphadmin:
    persistence:
      storageClassOverride: "efs-sc"
appc:
  enabled: false
cds:
  enabled: true
  cds-blueprints-processor:
    persistence:
      storageClassOverride: "efs-sc"
  
clamp:
  enabled: true
cli:
  enabled: true
# Today, "contrib" chart that hosting these components must also be enabled
# in order to make it work. So `contrib.enabled` must have the same value than
# addTestingComponents
contrib:
  enabled: true
  netbox:
    netbox-app:
      persistence:
        storageClassOverride: "efs-sc"
    netbox-nginx:
      persistence:
        storageClassOverride: "efs-sc"
consul:
  enabled: true
cps:
  enabled: true
dcaegen2:
  enabled: true
dcaegen2-services:
  enabled: true
dcaemod:
  enabled: true
  dcaemod-genprocessor:
    persistence:
      storageClassOverride: "efs-sc"
  
holmes:
  enabled: true
dmaap:
  enabled: true
oof:
  enabled: true
msb:
  enabled: true
multicloud:
  enabled: true
nbi:
  enabled: true
policy:
  enabled: true
portal:
  enabled: true
  portal-mariadb:
    config:
      sdcFePort: "9443"
robot:
  enabled: true
sdc:
  enabled: true
sdnc:
  enabled: true
so:
  enabled: true
uui:
  enabled: true
vfc:
  enabled: true
vid:
  enabled: true
vnfsdk:
  enabled: true
modeling:
  enabled: true
platform:
  enabled: true
a1policymanagement:
  enabled: true
